# Fragile Families Team Day 2: Working with data (Python, Numpy, Pandas)

If you want to read more, the following sites are helpful:

https://cloudxlab.com/blog/numpy-pandas-introduction/

https://www.hackerearth.com/practice/machine-learning/data-manipulation-visualisation-r-python/tutorial-data-manipulation-numpy-pandas-python/tutorial/

## Data types and Data structures in Python

#### Data type vs Data structure:

A data type is a classification of the data which tells the compiler or interpreter how the information will be used (Wikipedia, 2018). A data structure is a structure that holds data and has specific operations (or actions) that can be performed on it. (https://www.quora.com/What-is-the-difference-between-a-data-type-and-a-data-structure)

#### Data types

Exhaustive list of Data Types: http://developer.rhino3d.com/guides/rhinopython/python-datatypes/

Data types in Python include integers (5), floating point numbers (5.0), strings ("5", '5')

You can check a type of any variable by callig the type() command

In [3]:
k = 5
print(k,type(k))
l  = 5.0
print(l,type(l))
m = "5"
print(m,type(m))

5 <class 'int'>
5.0 <class 'float'>
5 <class 'str'>


The most important data structures in Python are lists, tuples and dictionaries.

### Lists

In [57]:
l = [1, 2, 7, 8]

In [39]:
a = [1, 4.5, 7, "hi", 'cat']

Elements of the list do not have to be of the same *type*. This is not true in other languages (they would all have to be integers or strings or floats...)

We can select elements of the list by the *index* of an element (note that in computer science we start counting at 0, not 1!):

In [37]:
a[0]

1

In [40]:
a[3]

'hi'

In [ ]:
We can add numbers toge

We can check the length of the list by calling *len()*

In [48]:
len(a)

5

In a way, a string is very much like a list. We can also access characters in a string using this indexing:

In [ ]:
a[3][1]

In [42]:
b = "squirrel"

In [43]:
b[0]

's'

In [49]:
len(b)

8

We can also express a string explicitly as a list:

In [45]:
list(b)

['s', 'q', 'u', 'i', 'r', 'r', 'e', 'l']

With numerical lists, we can use various operations, such as max, min, sum

In [50]:
c = [2, 46, 6, 866, 2]

In [51]:
min(c)

2

In [52]:
max(c)

866

In [54]:
sum(c)

922

### Tuples

### Dictionaries

# Numpy and Pandas

Numpy and Pandas are Python *libraries* - sets of functions that have been developed by others and shared openly for everyone to use. One of the reasons Python is so popular for AI is because of the comprehensive and fast libraries that have been developed and open sourced.

Libraries have to be downloaded before they're used (we did it already) and then *imported* in each Python file where you want to use them:

In [2]:
import numpy as np
import pandas as pd

The *as np* and *as pd* parts are meant to make calling those libraries easier - so you don't have to type *numpy* and *pandas* all the time

## Numpy

The basic *data structure* in numpy is an *array*:

1D array:

In [8]:
ar_1d = np.array([1,2,3])

In [9]:
print(ar_1d)
print(ar_1d.shape)

[1 2 3]
(3,)


2D array:

In [11]:
ar_2d = np.array([[1,2,3],[4,5,6]])

In [12]:
print(ar_2d)
print(ar_2d.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


3D array:

In [14]:
ar_3d = np.array([[1,2,3],[4,5,6],[9,8,7]])

In [15]:
print(ar_3d)
print(ar_3d.shape)

[[1 2 3]
 [4 5 6]
 [9 8 7]]
(3, 3)


#### Example: define two arrays (a and b) shaped 2x5, and add them together.

In [16]:
a = np.array([[1,1,1,1,1],[2,2,2,2,2],[1,1,1,1,1],[2,2,2,2,2],[1,1,1,1,1]])

In [17]:
b = np.array([[3,3,3,3,3],[1,1,1,1,1],[3,3,3,3,3],[1,1,1,1,1],[3,3,3,3,3]])

In [18]:
a+b

array([[4, 4, 4, 4, 4],
       [2, 2, 2, 2, 2],
       [4, 4, 4, 4, 4],
       [2, 2, 2, 2, 2],
       [4, 4, 4, 4, 4]])

#### Exercise: define two arrays (c and d) shaped 4x5, and add them together.

#### We can define arrays with predefined values:

All ones:

In [19]:
np.ones((2,2)) # the input is the shape of the array you want

array([[ 1.,  1.],
       [ 1.,  1.]])

In [21]:
np.ones((6,2)) # the input is the shape of the array you want

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

All zeros:

In [22]:
np.zeros((6,2)) # the input is the shape of the array you want

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

Random numbers (often useful in machine learning!)

In [25]:
np.random.rand(2,3) # the input is the shape of the array you want

array([[ 0.88214536,  0.56368043,  0.13003088],
       [ 0.05005386,  0.15161516,  0.41571759]])

We can also read excel-like files into numpy.

In [ ]:
np.load()